# -*- coding: utf-8 -*-
#
# Copyright (c) 2016, Marcelo Jorge Vieira <metal@alucinados.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

fields2010 = [
    'data_geracao',
    'hora_geracao',
    'ano_eleicao',
    'num_turno',
    'descricao_eleicao',
    'sigla_uf',
    'sigla_ue',
    'descricao_ue',
    'codigo_cargo',
    'descricao_cargo',
    'nome_candidato',
    'sequencial_candidato',
    'numero_candidato',
    'cpf_candidato',
    'nome_urna_candidato',
    'cod_situacao_candidatura',
    'des_situacao_candidatura',
    'numero_partido',
    'sigla_partido',
    'nome_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'codigo_ocupacao',
    'descricao_ocupacao',
    'data_nascimento',
    'num_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'codigo_sexo',
    'descricao_sexo',
    'cod_grau_instrucao',
    'descricao_grau_instrucao',
    'codigo_estado_civil',
    'descricao_estado_civil',
    'codigo_nacionalidade',
    'descricao_nacionalidade',
    'sigla_uf_nascimento',
    'codigo_municipio_nascimento',
    'nome_municipio_nascimento',
    'despesa_max_campanha',
    'cod_sit_tot_turno',
    'desc_sit_tot_turno',
]

fields2012 = [
    'data_geracao',
    'hora_geracao',
    'ano_eleicao',
    'num_turno',
    'descricao_eleicao',
    'sigla_uf',
    'sigla_ue',
    'descricao_ue',
    'codigo_cargo',
    'descricao_cargo',
    'nome_candidato',
    'sequencial_candidato',
    'numero_candidato',
    'cpf_candidato',
    'nome_urna_candidato',
    'cod_situacao_candidatura',
    'des_situacao_candidatura',
    'numero_partido',
    'sigla_partido',
    'nome_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'codigo_ocupacao',
    'descricao_ocupacao',
    'data_nascimento',
    'num_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'codigo_sexo',
    'descricao_sexo',
    'cod_grau_instrucao',
    'descricao_grau_instrucao',
    'codigo_estado_civil',
    'descricao_estado_civil',
    'codigo_nacionalidade',
    'descricao_nacionalidade',
    'sigla_uf_nascimento',
    'codigo_municipio_nascimento',
    'nome_municipio_nascimento',
    'despesa_max_campanha',
    'cod_sit_tot_turno',
    'desc_sit_tot_turno',
    'nm_email',
]

fields2014 = [
    'data_geracao',
    'hora_geracao',
    'ano_eleicao',
    'num_turno',
    'descricao_eleicao',
    'sigla_uf',
    'sigla_ue',
    'descricao_ue',
    'codigo_cargo',
    'descricao_cargo',
    'nome_candidato',
    'sequencial_candidato',
    'numero_candidato',
    'cpf_candidato',
    'nome_urna_candidato',
    'cod_situacao_candidatura',
    'des_situacao_candidatura',
    'numero_partido',
    'sigla_partido',
    'nome_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'codigo_ocupacao',
    'descricao_ocupacao',
    'data_nascimento',
    'num_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'codigo_sexo',
    'descricao_sexo',
    'cod_grau_instrucao',
    'descricao_grau_instrucao',
    'codigo_estado_civil',
    'descricao_estado_civil',
    'codigo_cor_raca',
    'descricao_cor_raca',
    'codigo_nacionalidade',
    'descricao_nacionalidade',
    'sigla_uf_nascimento',
    'codigo_municipio_nascimento',
    'nome_municipio_nascimento',
    'despesa_max_campanha',
    'cod_sit_tot_turno',
    'desc_sit_tot_turno',
    'nm_email',
]

year_headers = {
    '1996': fields2010,
    '1998': fields2010,
    '2000': fields2010,
    '2002': fields2010,
    '2004': fields2010,
    '2006': fields2010,
    '2008': fields2010,
    '2010': fields2010,
    '2012': fields2012,
    '2014': fields2014,
    '2016': fields2014,
}
