# -*- coding: utf-8 -*-
#
# Copyright (c) 2016, Marcelo Jorge Vieira <metal@alucinados.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

fields2010 = [
    'dt_geracao',
    'hh_geracao',
    'ano_eleicao',
    'nr_turno',
    'ds_eleicao',
    'sg_uf',
    'sg_ue',
    'nm_ue',
    'cd_cargo',
    'ds_cargo',
    'nm_candidato',
    'sq_candidato',
    'nr_candidato',
    'nr_cpf_candidato',
    'nm_urna_candidato',
    'cd_situacao_candidatura',
    'ds_situacao_candidatura',
    'nr_partido',
    'sg_partido',
    'nm_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'cd_ocupacao',
    'ds_ocupacao',
    'dt_nascimento',
    'nr_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'cd_genero',
    'ds_genero',
    'cd_grau_instrucao',
    'ds_grau_instrucao',
    'cd_estado_civil',
    'ds_estado_civil',
    'cd_nacionalidade',
    'ds_nacionalidade',
    'sg_uf_nascimento',
    'cd_municipio_nascimento',
    'nm_municipio_nascimento',
    'nr_despesa_max_campanha',
    'cd_sit_tot_turno',
    'ds_sit_tot_turno',
]

fields2012 = [
    'dt_geracao',
    'hh_geracao',
    'ano_eleicao',
    'nr_turno',
    'ds_eleicao',
    'sg_uf',
    'sg_ue',
    'nm_ue',
    'cd_cargo',
    'ds_cargo',
    'nm_candidato',
    'sq_candidato',
    'nr_candidato',
    'nr_cpf_candidato',
    'nm_urna_candidato',
    'cd_situacao_candidatura',
    'ds_situacao_candidatura',
    'nr_partido',
    'sg_partido',
    'nm_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'cd_ocupacao',
    'ds_ocupacao',
    'dt_nascimento',
    'nr_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'cd_genero',
    'ds_genero',
    'cd_grau_instrucao',
    'ds_grau_instrucao',
    'cd_estado_civil',
    'ds_estado_civil',
    'cd_nacionalidade',
    'ds_nacionalidade',
    'sg_uf_nascimento',
    'cd_municipio_nascimento',
    'nm_municipio_nascimento',
    'nr_despesa_max_campanha',
    'cd_sit_tot_turno',
    'ds_sit_tot_turno',
    'nm_email',
]

fields2014 = [
    'dt_geracao',
    'hh_geracao',
    'ano_eleicao',
    'nr_turno',
    'ds_eleicao',
    'sg_uf',
    'sg_ue',
    'nm_ue',
    'cd_cargo',
    'ds_cargo',
    'nm_candidato',
    'sq_candidato',
    'nr_candidato',
    'nr_cpf_candidato',
    'nm_urna_candidato',
    'cd_situacao_candidatura',
    'ds_situacao_candidatura',
    'nr_partido',
    'sg_partido',
    'nm_partido',
    'codigo_legenda',
    'sigla_legenda',
    'composicao_legenda',
    'nome_legenda',
    'cd_ocupacao',
    'ds_ocupacao',
    'dt_nascimento',
    'nr_titulo_eleitoral_candidato',
    'idade_data_eleicao',
    'cd_genero',
    'ds_genero',
    'cd_grau_instrucao',
    'ds_grau_instrucao',
    'cd_estado_civil',
    'ds_estado_civil',
    'cd_cor_raca',
    'ds_cor_raca',
    'cd_nacionalidade',
    'ds_nacionalidade',
    'sg_uf_nascimento',
    'cd_municipio_nascimento',
    'nm_municipio_nascimento',
    'nr_despesa_max_campanha',
    'cd_sit_tot_turno',
    'ds_sit_tot_turno',
    'nm_email',
]

year_headers = {
    '1996': fields2010,
    '1998': fields2010,
    '2000': fields2010,
    '2002': fields2010,
    '2004': fields2010,
    '2006': fields2010,
    '2008': fields2010,
    '2010': fields2010,
    '2012': fields2012,
    '2014': [],
    '2016': [],
    '2018': [],
}
